### ISSUE TITLE
$(document).ajaxComplete doesn't fire

### ISSUE THREAD

**Issue by vialcollet** [APY/APYDataGridBundle#1013] opened 2018-06-21 15:58 UTC
When I use either filters or pagination, the ajaxComplete function is not called?

In other pages where APYDataGridBundle is not used this is behaving as expected.
Ant idea why?

**Comment by vialcollet** [comment] 2018-06-21 16:50
It was ok until I migrated from Symfony 2.8 to Symfony 3.4 (from scratch) and started to use Webpack.
I don't know if Webpack could be the issue (and why ony with grids?). I just tried by-passing Webpack and the behaviour is the same.

ajaxStart() is not triggered either. The code is there though...

The following is loaded everywhere:
```
jQuery(document).ready(function() {
    Initialize();
    MyStyle();
    searchService();
    searchCountry();
    betterSubmitUI;
});

function Initialize() {
    jQuery(document).ajaxComplete(function() {
        MyStyle();
    });


    jQuery(document).ajaxStart(function(){
        console.log("ajaxStart");
    });

}

function MyStyle() {
...
}
```

**Comment by npotier** [comment] 2020-04-01 14:05
Hello @vialcollet I'm not able to reproduce this issue.

Since this issue is old, I'm closing it. Feel free to reopen it with an example describing the problem.

**Closed by npotier** 2020-04-01 14:05 UTC
