### ISSUE TITLE
filters passed in GET

### ISSUE THREAD

**Issue by Fidesio-Thomas** [APY/APYDataGridBundle#936] opened 2017-04-10 08:46 UTC

**Comment by DonCallisto** [comment] 2017-04-10 08:47
This issue is a duplicate of this --> https://github.com/APY/APYDataGridBundle/issues/829

AFAIK @qferr is working on it.

**Comment by Fidesio-Thomas** [comment] 2017-04-10 08:48
Thanks @DonCallisto

**Closed by DonCallisto** 2017-04-10 08:47 UTC
