### ISSUE TITLE
How can I manage to install latest release of APY@3.1.0 on SF@3.4

### ISSUE THREAD

**Issue by EloneSampaio** [APY/APYDataGridBundle#999] opened 2018-02-02 16:52 UTC
Hi.

I have started a project as SF 3.4 and I've tried to install APY. So the error came out:

Your requirements could not be resolved to an installable set of packages.

After that I tried:

composer require apy/datagrid-bundle@3.1.0

Could not find package apy/datagrid-bundle@3.1.0 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Unlike 3.4, It perfectly installs APY@3.0 on SF@3.3

How can I manage to install latest release of APY@3.1.0 on SF@3.4

**Comment by kannanseeni** [comment] 2018-02-04 07:55
Try
$ composer require apy/datagrid-bundle --ignore-platform-reqs

**Comment by EloneSampaio** [comment] 2018-02-04 18:56
Not working @kannanseeni

**Comment by DonCallisto** [comment] 2018-02-15 07:46
Duplicate of #994

**Closed by DonCallisto** 2018-02-15 07:46 UTC
