### ISSUE TITLE
Latest commit throws an metdata exception

### ISSUE THREAD

**Issue by vialcollet** [APY/APYDataGridBundle#720] opened 2015-05-11 18:38 UTC
Hi there after updating to the latest dev-master, my Symfony 2.3 app is now throwing the following exception: No metadata information has been found.
I saw that this is due to the fact that if there is no annotation in a given entity/group.
I would suggest that such versions are properly tagged in order to avoid such issues.
If my understanding is correct, the only quick solution is to require 2.1.15, correct?
Thanks !

**Comment by Abhoryo** [comment] 2015-05-11 21:06
Sorry for the mess

**Comment by npotier** [comment] 2015-05-11 21:39
Hi @vialcollet thanks for the feedback. I'll try to reproduce this behaviour and fix it asap.

Nicolas.

**Comment by Tjeerd** [comment] 2015-06-10 12:48
@Abhoryo: please release a new version equal to 2.1.15 asap! Every new install or update will now get a broken version!

**Comment by asgarciap** [comment] 2015-07-03 03:34
Hi!
The last version is still broken at this point. Last night updated to 2.2.16 version failed with same error mentioned here.
Please, a new version will be nice!

**Comment by milan74sk** [comment] 2015-09-02 08:07
When will be released fixed version please ?

**Comment by qferr** [comment] 2015-12-21 16:25
#773

**Comment by qferr** [comment] 2016-03-06 11:33
This issue does not exist in master. 

@APY/collaborators If we support the BC version 2.2, we should fix on this version.

**Comment by hmert** [comment] 2016-03-07 04:59
yes, we should. Because 2.2 should not have a bug.

**Comment by hmert** [comment] 2016-10-01 22:12
https://github.com/APY/APYDataGridBundle/releases/tag/2.2.17 this tag fixes

**Closed by hmert** 2016-10-01 22:12 UTC
Labels: Bug
