### ISSUE TITLE
[Syntax Error] Lexer::T_FROM got ':'

### ISSUE THREAD

**Issue by Dakhtara** [APY/APYDataGridBundle#1000] opened 2018-02-17 17:31 UTC
Hi,

I am using the 3.0.2 version of APYDataGrid.
Everything works fine except when I try to associate a column.
I have followed the doc about it.
```php
/**
 * Image
 *
 * @ORM\Table()
 * @ORM\Entity
 * @Vich\Uploadable
 * @GRID\Source(columns="id, path, imageName, game.title, createdAt", groupBy={"id"})
 */
class Image
{


   /**
     * @var Jeux
     * @ORM\ManyToOne()
     * @GRID\Column(field="game.title" ,title="Jeux", filter="select", selectFrom="query")
     */
    private $game;
}
```
It worked when i was on SF 2.8. But after upgrading it doesn't work anymore.

It works if i delete the column. But at the moment I add it it send me the error : 
[Syntax Error] line 0, col 69: Error: Expected Doctrine\ORM\Query\Lexer::T_FROM, got ':'

It doesn't look Doctrine works wrong
Do you have any idea about it ? Thanks

**Comment by DonCallisto** [comment] 2018-02-17 17:33
Duplicate of #772

**Closed by DonCallisto** 2018-02-17 17:33 UTC

**Comment by DonCallisto** [comment] 2018-03-31 10:47
I've drafted a new release for this https://github.com/APY/APYDataGridBundle/releases/tag/3.1.2
